import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import { Plane, Map, Calendar, Shield, Sparkles, Globe, Clock, Heart } from "lucide-react";

const KnowMorePage = () => {
  const features = [
    {
      icon: Plane,
      title: "Smart Flight Booking",
      description: "Find the best flight deals with our AI-powered search engine that compares thousands of routes.",
      color: "from-blue-500 to-cyan-500",
    },
    {
      icon: Map,
      title: "Interactive Maps",
      description: "Explore destinations with our immersive 3D maps showing hotels, attractions, and hidden gems.",
      color: "from-purple-500 to-pink-500",
    },
    {
      icon: Calendar,
      title: "Instant Itineraries",
      description: "Get personalized day-by-day travel plans generated by AI based on your preferences.",
      color: "from-orange-500 to-red-500",
    },
    {
      icon: Shield,
      title: "Secure Booking",
      description: "Book with confidence. Your payments and personal data are protected with bank-level security.",
      color: "from-green-500 to-emerald-500",
    },
    {
      icon: Sparkles,
      title: "AI Travel Assistant",
      description: "Chat with our intelligent assistant 24/7 for instant answers about destinations and bookings.",
      color: "from-yellow-500 to-orange-500",
    },
    {
      icon: Globe,
      title: "Global Coverage",
      description: "Access thousands of destinations worldwide with real-time pricing and availability.",
      color: "from-indigo-500 to-purple-500",
    },
    {
      icon: Clock,
      title: "Real-Time Updates",
      description: "Get instant notifications about flight changes, gate info, and travel alerts.",
      color: "from-pink-500 to-rose-500",
    },
    {
      icon: Heart,
      title: "Personalized Experience",
      description: "Save favorites, compare plans, and get recommendations based on your travel style.",
      color: "from-teal-500 to-cyan-500",
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="pt-20 pb-12">
        {/* Hero Section */}
        <section className="relative overflow-hidden py-20">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-secondary/10 to-background" />
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="container mx-auto px-4 relative z-10"
          >
            <div className="text-center max-w-4xl mx-auto">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
                className="inline-block mb-6"
              >
                <div className="w-20 h-20 mx-auto rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
                  <Plane className="w-10 h-10 text-white" />
                </div>
              </motion.div>
              
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="text-5xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-primary via-secondary to-primary bg-clip-text text-transparent"
              >
                Your Journey, Reimagined
              </motion.h1>
              
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="text-xl text-muted-foreground mb-8"
              >
                Welcome to TravelAI - where artificial intelligence meets wanderlust. 
                We've revolutionized the way you plan, book, and experience travel.
              </motion.p>

              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.5 }}
                className="flex flex-wrap justify-center gap-4 text-sm"
              >
                <div className="px-6 py-3 bg-primary/10 rounded-full">
                  <span className="font-semibold text-primary">500K+</span> Happy Travelers
                </div>
                <div className="px-6 py-3 bg-secondary/10 rounded-full">
                  <span className="font-semibold text-secondary">1000+</span> Destinations
                </div>
                <div className="px-6 py-3 bg-primary/10 rounded-full">
                  <span className="font-semibold text-primary">24/7</span> AI Support
                </div>
              </motion.div>
            </div>
          </motion.div>

          {/* Animated Background Elements */}
          <div className="absolute inset-0 overflow-hidden pointer-events-none">
            {[...Array(20)].map((_, i) => (
              <motion.div
                key={i}
                className="absolute w-2 h-2 bg-primary/20 rounded-full"
                initial={{
                  x: Math.random() * window.innerWidth,
                  y: Math.random() * window.innerHeight,
                }}
                animate={{
                  y: [null, Math.random() * window.innerHeight],
                  opacity: [0, 1, 0],
                }}
                transition={{
                  duration: Math.random() * 10 + 10,
                  repeat: Infinity,
                  ease: "linear",
                }}
              />
            ))}
          </div>
        </section>

        {/* Features Grid */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl font-bold mb-4">Powered by Innovation</h2>
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                Experience the future of travel with our cutting-edge features designed to make your journey seamless and memorable.
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              {features.map((feature, index) => {
                const Icon = feature.icon;
                return (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: index * 0.1 }}
                    whileHover={{ y: -10, scale: 1.02 }}
                    className="relative group"
                  >
                    <div className="h-full bg-card rounded-2xl p-6 border border-border shadow-[var(--shadow-medium)] hover:shadow-[var(--shadow-strong)] transition-all duration-300">
                      <motion.div
                        whileHover={{ rotate: 360 }}
                        transition={{ duration: 0.6 }}
                        className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${feature.color} flex items-center justify-center mb-4`}
                      >
                        <Icon className="w-7 h-7 text-white" />
                      </motion.div>
                      
                      <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                      <p className="text-muted-foreground text-sm leading-relaxed">
                        {feature.description}
                      </p>

                      {/* Animated border on hover */}
                      <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br ${feature.color} opacity-0 group-hover:opacity-20 transition-opacity duration-300 -z-10`} />
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="py-20 bg-muted/30">
          <div className="container mx-auto px-4">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-center mb-16"
            >
              <h2 className="text-4xl font-bold mb-4">How TravelAI Works</h2>
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                From dreaming about your destination to boarding your flight, we've got you covered every step of the way.
              </p>
            </motion.div>

            <div className="max-w-4xl mx-auto">
              {[
                { step: "01", title: "Tell Us Your Dream", desc: "Chat with our AI about where you want to go, your budget, and travel style." },
                { step: "02", title: "Get Instant Plans", desc: "Receive personalized itineraries with flights, hotels, and activities in seconds." },
                { step: "03", title: "Compare & Customize", desc: "Review options, compare prices, and tweak your plan until it's perfect." },
                { step: "04", title: "Book & Travel", desc: "Secure booking with one click and get real-time updates throughout your journey." },
              ].map((item, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: index % 2 === 0 ? -50 : 50 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.2 }}
                  className="relative flex items-start gap-6 mb-12 last:mb-0"
                >
                  <div className="flex-shrink-0 w-16 h-16 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-white font-bold text-xl">
                    {item.step}
                  </div>
                  <div className="flex-1 bg-card rounded-2xl p-6 border border-border shadow-[var(--shadow-soft)]">
                    <h3 className="text-2xl font-semibold mb-2">{item.title}</h3>
                    <p className="text-muted-foreground">{item.desc}</p>
                  </div>
                  
                  {index < 3 && (
                    <motion.div
                      initial={{ scaleY: 0 }}
                      whileInView={{ scaleY: 1 }}
                      viewport={{ once: true }}
                      transition={{ delay: index * 0.2 + 0.3 }}
                      className="absolute left-8 top-20 w-0.5 h-12 bg-gradient-to-b from-primary to-secondary origin-top"
                    />
                  )}
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="container mx-auto px-4"
          >
            <div className="relative overflow-hidden bg-gradient-to-br from-primary via-secondary to-primary rounded-3xl p-12 md:p-16 text-center">
              <div className="relative z-10">
                <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                  Ready to Start Your Adventure?
                </h2>
                <p className="text-xl text-white/90 mb-8 max-w-2xl mx-auto">
                  Join thousands of travelers who've discovered a smarter way to explore the world.
                </p>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => window.location.href = "/chat"}
                  className="px-8 py-4 bg-white text-primary font-semibold rounded-full shadow-lg hover:shadow-xl transition-all"
                >
                  Start Planning Now →
                </motion.button>
              </div>

              {/* Animated circles */}
              <div className="absolute inset-0 overflow-hidden">
                {[...Array(5)].map((_, i) => (
                  <motion.div
                    key={i}
                    className="absolute rounded-full border-2 border-white/20"
                    style={{
                      width: 100 + i * 100,
                      height: 100 + i * 100,
                      left: "50%",
                      top: "50%",
                      marginLeft: -(50 + i * 50),
                      marginTop: -(50 + i * 50),
                    }}
                    animate={{
                      scale: [1, 1.2, 1],
                      opacity: [0.3, 0.1, 0.3],
                    }}
                    transition={{
                      duration: 3 + i,
                      repeat: Infinity,
                      ease: "easeInOut",
                    }}
                  />
                ))}
              </div>
            </div>
          </motion.div>
        </section>
      </main>
    </div>
  );
};

export default KnowMorePage;
